#include<stdio.h>
#include<stdlib.h>
#include<math.h>
#include "power_mod.h"

int verify(int p,int g,int a,int b)
{
	int A, B, k_alice, k_bob;

	A = pow_mod(g, a, p);
	B = pow_mod(g, b, p);
	k_alice = pow_mod(B, a, p);
	k_bob = pow_mod(A, b, p);

	printf("\nKey generated by alice=%d", k_alice);
	printf("\nKey generated by bob=%d", k_bob);
	
    if(k_alice == k_bob)
		return 1;
	else
		return 0;
	
}

int main(int argc, char** argv)
{
    if(argc<5) {
        printf("\nUsage: %s <p> <g> <a> <b>\n", argv[0]);
        return 0;
    }

	if(verify(atoi(argv[1]), atoi(argv[2]), atoi(argv[3]), atoi(argv[4])))
		printf("\nBoth keys are same\n\n");
	else
		printf("\nKeys are different\n\n");
}

